
'use client';

import Link from 'next/link';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { GraduationCap, LineChart, ChevronRight } from 'lucide-react';

const trainingOptions = [
  {
    title: 'AI-Powered Quiz',
    description: 'Test and improve your trading knowledge with questions generated by AI.',
    href: '/training/quiz',
    icon: GraduationCap,
  },
  {
    title: 'Interactive Practice Charts',
    description: 'Use a live, interactive chart to practice your technical analysis skills in real-time.',
    href: '/training/charts',
    icon: LineChart,
  },
];

export default function TrainingHubPage() {
  return (
    <div className="container mx-auto py-4 px-2 md:px-0 max-w-2xl">
      <div className="space-y-4">
        <Card>
            <CardHeader>
                <CardTitle className="text-xl">Training Center</CardTitle>
                <CardDescription>Choose an activity to sharpen your trading skills.</CardDescription>
            </CardHeader>
        </Card>

        <div className="grid grid-cols-1 md:grid-cols-1 gap-4">
          {trainingOptions.map((option) => (
            <Link href={option.href} key={option.href} className="block hover:no-underline">
              <Card className="h-full hover:border-primary/50 hover:bg-muted/30 transition-all">
                <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                  <div className="flex items-center">
                    <div className="bg-primary/10 p-2 rounded-md mr-3">
                        <option.icon className="h-5 w-5 text-primary" />
                    </div>
                    <div>
                        <CardTitle className="text-md font-medium">{option.title}</CardTitle>
                    </div>
                  </div>
                  <ChevronRight className="h-5 w-5 text-muted-foreground" />
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground pl-11">{option.description}</p>
                </CardContent>
              </Card>
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
}
